---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: servicegraph
  namespace: istio-system
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: servicegraph
    spec:
      containers:
      - name: servicegraph
        image: docker.io/istio/servicegraph:0.2.7
        ports:
          - containerPort: 8088
        args:
        - --prometheusAddr=http://prometheus:9090
---
apiVersion: v1
kind: Service
metadata:
  name: servicegraph
  namespace: istio-system
spec:
  type: LoadBalancer
  externalIPs:
  - $HOST_IP
  ports:
  - name: http
    port: 8088
  selector:
    app: servicegraph
---
